version: "3.6"

# https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Docker-Compose
# https://blog.ippon.tech/set-up-a-reverse-proxy-nginx-and-docker-gen-bonus-lets-encrypt/
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose
# https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose/blob/master/2-containers/compose-v3/environment/docker-compose.yaml

networks:
  sister:
    name: sister
      external:true

services:
  web:
    # http://web456-104-193-61-58.nip.io/
    # https://web456-104-193-61-58.nip.io/
    image: nginx:1.15-alpine
    # container_name: example-webapp
    volumes:
      - ./nindex.html:/usr/share/nginx/html/index.html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=web456-104-193-61-58.nip.io
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=web456-104-193-61-58.nip.io
      - LETSENCRYPT_EMAIL=dgleba@gmail.com
    restart: always
    networks:
      - sister

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d
      - ./vol/nginx/certs:/etc/nginx/certs:ro
      - ./vol/nginx/html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - sister

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vol/nginx/vhost.d:/etc/nginx/vhost.d
      - ./vol/nginx/certs:/etc/nginx/certs:rw
      - ./vol/nginx/html:/usr/share/nginx/html
    networks:
      - sister
    # links will share the volumes between containers.
    links:
      - nginx-proxy
####
#   mysql:
#     image: mysql:8.0.3
#     hostname: mysql
#     ports:
#         - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: owncloud
#       MYSQL_USER: ippon
#       MYSQL_PASSWORD: ippon
#     networks:
#       - ippon
# owncloud:
#     image: owncloud:10.0.3
#     hostname: owncloud
#     ports:
#       - "8080:80"
#     networks:
#       - ippon
#     environment:
#       VIRTUAL_HOST: cloud.ippon.local
#       VIRTUAL_PORT: 8080
# nginx:
#   image: nginx:1.14-alpine
#   restart: always
#   ports:
#     - 6314:80
#   volumes:
#     - ./nindex.html:/usr/share/nginx/html/index.html
# apache:
#   image: php:7.2-apache
#   restart: always
#   ports:
#     - 6316:80
#   volumes:
#     - ./aindex.html:/var/www/html/index.html
